Start:Compile Run											

Compile:Node Iterator DoublyList Main							
	g++ ./lib/Node.o ./lib/Iterator.o ./lib/DoublyList.o ./lib/main.o -o ./bin/program.exe		
Node:														
	g++ -I "./include" -c ./src/Node.cpp -o ./lib/Node.o	
Iterator:
	g++ -I "./include" -c ./src/Iterator.cpp -o ./lib/Iterator.o
DoublyList:
	g++ -I "./include" -c ./src/DoublyList.cpp -o ./lib/DoublyList.o
Main:
	g++ -I "./include" -c ./src/main.cpp -o ./lib/main.o
	
Run:
	./bin/program.exe											
	